apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
  - namespace.yaml
  - scc.yaml
  - zookeeper-hub.yaml
  - metric-creds.yaml
  - credential.yaml
  - c3-mds-client.yaml
  - ca-pair-sslcerts.yaml
  - kafka.yaml
  - basicauth.yaml
  - controlcenter-hybrid.yaml
  - control-center-route.yaml

patchesJson6902:
- target:
    kind: ServiceExport
    name: zookeeper-hybrid-0-internal
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: east
- target:
    kind: ServiceExport
    name: zookeeper-hybrid-1-internal
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: east
- target:
    kind: ServiceExport
    name: zookeeper-hybrid-2-internal
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: east
- target:
    kind: ServiceExport
    name: zookeeper-hybrid
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: east