apiVersion: security.openshift.io/v1
fsGroup:
  type: MustRunAs
  ranges:
    # Here, the allowed group ID is configured to be between 1001 and 1005.
    - min: 1001
      max: 1005
groups:
  - system:authenticated
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: scc configuration for confluent components
  name: confluent-operator
priority: 10
requiredDropCapabilities:
  - MKNOD
runAsUser:
   # Here, the allowed user ID is configured to be between 1000 and 1005
  type: MustRunAsRange
  uidRangeMin: 1000
  uidRangeMax: 1005
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret