apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper-hybrid
  namespace: east
  annotations:
    platform.confluent.io/zookeeper-myid-offset: "10"
spec:
  configOverrides:
    peers:
      - server.10=zookeeper-hybrid-0.zookeeper-hybrid.east.svc.cluster.local:2888:3888
      - server.11=zookeeper-hybrid-1.zookeeper-hybrid.east.svc.cluster.local:2888:3888
      - server.12=zookeeper-hybrid-2.zookeeper-hybrid.east.svc.cluster.local:2888:3888
      - 'server.20=zookeeper-hybrid-0-internal.west.svc.clusterset.local:2888:3888'
      - 'server.21=zookeeper-hybrid-1-internal.west.svc.clusterset.local:2888:3888'
    server:
      - electionPortBindRetry=25
  dataVolumeCapacity: 10Gi
  image:
    application: 'confluentinc/cp-zookeeper:7.3.3'
    init: 'confluentinc/confluent-init-container:2.5.2'
  logVolumeCapacity: 10Gi
  replicas: 3
