apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: default
  namespace: west
spec:
  kafkaRest:
    authentication:
      bearer:
        secretRef: kafka-rest-credential
      type: bearer
