apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - scc.yaml
  - zookeeper-cluster1.yaml 
  - metric-creds.yaml
  - credential.yaml
  - c3-mds-client.yaml
  - ca-pair-sslcerts.yaml
  - kafka.yaml
  - schemaregistry.yaml

patches:
- target:
    kind: ServiceExport
    name: zookeeper-hybrid-0-internal
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: west
- target:
    kind: ServiceExport
    name: zookeeper-hybrid-1-internal
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: west
- target:
    kind: ServiceExport
    name: zookeeper-hybrid-2-internal
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: west
- target:
    kind: ServiceExport
    name: zookeeper-hybrid
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: west
- target:
    kind: ServiceExport
    name: kafka-hybrid
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: west
- target:
    kind: ServiceExport
    name: kafka-hybrid-0-internal
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: west
- target:
    kind: ServiceExport
    name: kafka-hybrid-1-internal
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: west