apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper-hybrid
  namespace: west
  annotations:
    platform.confluent.io/zookeeper-myid-offset: "20"
spec:
  configOverrides:
    peers:
      - 'server.10=zookeeper-hybrid-0-internal.east.svc.clusterset.local:2888:3888'
      - 'server.11=zookeeper-hybrid-1-internal.east.svc.clusterset.local:2888:3888'
      - 'server.12=zookeeper-hybrid-2-internal.east.svc.clusterset.local:2888:3888'
      - 'server.20=zookeeper-hybrid-0.zookeeper-hybrid.west.svc.cluster.local:2888:3888'
      - 'server.21=zookeeper-hybrid-1.zookeeper-hybrid.west.svc.cluster.local:2888:3888'
    server:
     - electionPortBindRetry=25
  dataVolumeCapacity: 100Gi
  image:
    application: 'confluentinc/cp-zookeeper:7.3.3'
    init: 'confluentinc/confluent-init-container:2.5.2'
  logVolumeCapacity: 100Gi
  replicas: 2
